### ISSUE TITLE
Help using Rsession

### ISSUE THREAD

**Issue by srikanthBezawada** [yannrichet/rsession#14]
Hi,

I need to execute a R command which needs a file taken from user through Java GUI. So, I have _File f_. 
How do I send this file to process R command through Rsession? 

File file; // Taken from user
rsession.sendFile(file, "demo"); 

Thanks!

**Comment by yannrichet** [comment]
```java
Rsession r =new RenjinSession();
r.putFile(file,"myfile");
```
