### ISSUE TITLE
Error: long vectors not supported yet: qap_encode.c:36

### ISSUE THREAD

**Issue by subes** [yannrichet/rsession#20]
This seems to be a bug in Rserve 1.7-3 with R 3.5.

See: https://github.com/s-u/Rserve/search?q=long+vector&type=Issues

Is there some way to upgrade rserve?

**Comment by subes** [comment]
The problem for me is that any eval call results in a "write failed" exception due to the underlying rserve connection being closed. The log shows the error in the title: `Error: long vectors not supported yet: qap_encode.c:36`

So using rserve backend is not operational with R 3.5.

**Comment by subes** [comment]
This issue is also mentioned in the news for rserve 1.8-6: https://github.com/s-u/Rserve/blob/master/NEWS

**Comment by subes** [comment]
Rserve 1.8-6 seems to be available here: https://www.rforge.net/Rserve/files/

**Comment by subes** [comment]
I installed 1.8-6 myself using `install.packages("Rserve",,"http://rforge.net")` but the error still occurs.

**Comment by subes** [comment]
Nevermind. The lib.loc start parameter was causing rsession to use 1.7-3 which it installed itself.

**Comment by yannrichet** [comment]
Indeed, the standard 1.8-6 (available on parent github from Simon Urbanek) fixes the issue. I just backported it on 1.7 branch here (named arbitrary 1.7-5), because I needed to have it working on Windows / R 3.5 (which is one purpose of this repository).
Regards.

**Comment by subes** [comment]
Ah, ok so this will be fixed in 2.0.5 (which is not yet in maven repo), I was trying 2.0.4 and that still installed rserve 1.7-3.

**Comment by yannrichet** [comment]
Now in 3.0
Also, you can find my fork of rserve 1.7 (just including this dix) here 
https://github.com/yannrichet/Rserve-1.7/releases
