### ISSUE TITLE
2.0.4: [exception] eval failed, request status: error code: 127

### ISSUE THREAD

**Issue by subes** [yannrichet/rsession#21]
1.8.3 works fine.

I tried playing around with sinkOutput(true/false) and sinkMessage(true/false) and this resulted in either one of these error messages inside the R instance:

Error in close(.f) : Object '.f' not found
Error in close(.fm) : Object '.fm' not found

**Comment by subes** [comment]
Tested with R 3.5.1

**Comment by subes** [comment]
You should be able to reproduce this by checking out the following commit: https://github.com/subes/invesdwin-context-r/commit/2932b23ced912ce7f8dc6dfa36cd56310f71863c

And running the following test case: invesdwin-context-r-runtime-rserve/src/test/java/de/invesdwin/context/r/runtime/rserve/RserveScriptTaskRunnerRTest.java

**Comment by yannrichet** [comment]
Should be fixed now with 3.0
