### ISSUE TITLE
Rmd conversion by knitr into notebook (HTML, PDF or Word document) 

### ISSUE THREAD

**Issue by Astangul** [yannrichet/rsession#40]
![image](https://user-images.githubusercontent.com/11903502/101782763-b56cb480-3af9-11eb-9abe-19e64597ddff.png)

[EGO_2.zip](https://github.com/yannrichet/rsession/files/5673291/EGO_2.zip)

**Comment by yannrichet** [comment]
transferred to https://github.com/Funz/funz-client/issues/21
