### ISSUE TITLE
every time we use java rsession invoke remote rserve,one more rserve process will start

### ISSUE THREAD

**Issue by zhangkunpanda** [yannrichet/rsession#43]
wo use rsession(version is 1.8.3) connect to Rserve(version is 1.7.3) do some research,but every time we use java rsession invoke remote rserve,one more rserve process will start.

my code is :

RserverConf rconf = new RserverConf(rserveHost,rservePort, "","", new Properties());
Rsession rsess = Rsession.newInstanceTry(rlogger, rconf);

Thank you for your contribution；we are glad to get response from you。

thanks

**Comment by yannrichet** [comment]
This is the standard behavior. You can change this using the -DRSERVE_NO_INC_PORT=true in java command args (since Rsession 3.1.4)
