### ISSUE TITLE
Other statements cannot be executed after the end statement is executed

### ISSUE THREAD

**Issue by ZouZouZouJiYuan** [yannrichet/rsession#46]
![image](https://user-images.githubusercontent.com/115384618/194736077-952b7857-e6a0-4f76-80eb-0d651e96c1af.png)

When I execute session. end (); Statement, System. out. println ("end"); Not implemented

![image](https://user-images.githubusercontent.com/115384618/194736103-f910cacc-fa44-47c0-b708-e107bcfaea9f.png)

**Comment by yannrichet** [comment]
That demo just points that System.out stream is not well reset in the tests...
Indeed, the .end() is just closing rsession instance, which may redirect System.out (or may not, if you prefer a true logger).
