### ISSUE TITLE
Consider publishing maven site to github

### ISSUE THREAD

**Issue by kktuax** [yannrichet/rsession#7]
Now that we use maven we can publish the maven site with the Javadoc to GitHub pages using their site plugin: https://github.com/github/maven-plugins

**Comment by kktuax** [comment]
Result of "mvn site" after commit 4552949

http://predictia.github.io/rsession/

Note that ~/.m2/settings.xml must contain auth details:

```
<settings>
 <servers>
...
    <server>
     <id>github</id>
     <username>youruser</username>
     <password>yourpass</password>
   </server>
...
 </servers>
</settings>
```

**Comment by yannrichet** [comment]
done.
